# Generated by Django 4.2.4 on 2024-04-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
    ]
