version: "3.8"

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    command: ["sh", "./start.sh"]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - pgdb

  pgdb:
    container_name: pgdb
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data:
